# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish NPM

on:
  workflow_dispatch:
    inputs:
      vscode_version:
        description: 'The version of vscode upstream'
        required: true
        default: '1.95.3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Update vscode version for building
        run: |
          git config --global pull.rebase false
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # update version in package.json using sed
          sed -i "s/\"version\": \"[0-9]\+\.[0-9]\+\.[0-9]\"/\"version\": \"${{ github.event.inputs.vscode_version }}\"/g" package.json
          # update package-lock.json
          npm install
          git add package.json package-lock.json
          git commit -m "update vscode version to ${{ github.event.inputs.vscode_version }}" || true
          git tag ${{ github.event.inputs.vscode_version }} || true
          git push
          git push --tag
      - name: Setup Build Environment
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev libkrb5-dev python-is-python3
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
